### ISSUE TITLE
Conversation1

### ISSUE THREAD

**Issue by Taki21** [SWNetworkDevelopers/GithubChat#1]
Hey...So i deleted PHPStudio and will upload when almost finished!

**Comment by Taki21** [comment]
I am gonna make the website and HOST the app ONLY on Google Play Store

**Comment by PocketKiller** [comment]
...

**Comment by PocketKiller** [comment]
Use https://gitter.im

**Comment by Taki21** [comment]
Lol totaly forgot dat
